import type { NextPage } from "next";
import { useTheme } from "next-themes";
import Head from "next/head";
import Header from "../components/Header/Header";

const Home: NextPage = () => {
  const { theme, setTheme } = useTheme();

  return (
    <div>
      <Head>
        <title>Baitham | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full dark:bg-zinc-800 bg-white">
        <Header />
        <div className="h-screen flex items-center justify-center">
          <div>
            <h1 className="text-xl font-bold dark:text-white pb-8">
              Welcome to <a href="#">Next.js!</a>
            </h1>
            <button
              className="dark:bg-white dark:text-black border bg-black py-3 px-20 text-white"
              onClick={() => setTheme(theme === "light" ? "dark" : "light")}
            >
              {theme === "light" ? "Dark" : "Light"}
            </button>
          </div>
        </div>
      </main>

      <footer className="flex items-center justify-center h-32 dark:bg-gray-600 bg-gray-200">
        <h1 className="font-bold text-4xl dark:text-white text-black">
          THE END
        </h1>
      </footer>
    </div>
  );
};

export default Home;
