import type { NextPage } from "next";
import Head from "next/head";
import Pipeline from "../components/Pipeline/Pipeline";
import { Docs } from "../components";
import { Article } from "../components/Article/Article";
import Slider from "../components/Slider/Slider";

const Home: NextPage = () => {
  return (
    <div className="dark:bg-zinc-800 bg-white">
      <Head>
        <title>CodeAcademy | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full dark:bg-zinc-800 bg-white">
        <div className="pt-32">
          <Docs />
          <Article />
          <Pipeline />
          <Slider />
        </div>
      </main>
    </div>
  );
};

export default Home;
